[tool.poetry]
name = "meu-projeto"
version = "0.1.0"
description = "Projeto de exemplo com Poetry"
authors = ["Tiago Caixerta <tiago@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
